const carsInventory = [
  {
    id: "0101",
    Title: "CANNARY COUNTACH",
    Manufacturer: "Lamborghini",
    Model: "countach",
    Color: { title: "yellow", hex: "#FBBF24" },
    Year: "1986",
    Price: 250000,
    Desc: "The Countach’s story started in 1971 with the concept’s debut at the Geneva Motor Show. Designed by Marcello Gandini .In all, Lamborghini made five original Countach variants. The Giallo Fly yellow-painted 1988.5 model you see here is an LP5000 Quattrovalvole, also known as the QV. Arguably the most desirable of the bunch, it has the boldest design and a 5.2-liter V-12 engine with four valves per cylinder (hence the name). Ultra-flat, ultra-wide, and ultra-cool, it’s the epitome of Eighties excess. The phone dial wheels. The 345 section-width tires. The pop-up headlights. This car has it all. If any Countach can live up to its poster car reputation, it’s this one..",
    img1: "https://www.carscoops.com/wp-content/uploads/2023/05/Lamborghini-Countach-1-1024x683.jpg",
    img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStIC77sLJukkGOi7muSNdTlwy22zqMc_GJ-w&usqp=CAU",
    img3: "https://c4.wallpaperflare.com/wallpaper/459/941/209/yellow-cars-classic-car-lamborghini-countach-wallpaper-preview.jpg",
    img4: "https://c4.wallpaperflare.com/wallpaper/537/324/933/lamborghini-countach-classic-car-yellow-cars-wallpaper-preview.jpg",
  },
  {
    id: "0102",
    Title: "ROSSA RED",
    Manufacturer: "Ferrari",
    Model: "testarossa",
    Color: { title: "red", hex: "#DC2626" },
    Year: "1986",
    Price: 280000,
    Desc:'The Testarossa burst on to the 1980s supercar scene bearing a name that linked it back to the racing 250 Testa Rossa (‘red head’) of the ’50s but it was far from a barebones sports car. Introduced as a replacement for the Berlinetta Boxer, the Testarossa might have been very sporty but its generous dimensions and luxurious interior hinted at it being more of a fast grand tourer than a track day toy. Those signature side intake strakes (necessary to feed the side-mounted radiators) and angular styling could not have been more different from the BB’s smooth, flowing lines. Under the aggressively styled body was a well-balanced chassis and a revised 4.9-litre flat-12 with 180mph performance potential.',
    img1: "https://cdn.classic-trader.com/I/images/1920_1920_inset/vehicle_ad_standard_image_074956edc2cb1222c04acbb31b934823.jpg",
    img2: "https://cdn.wallpapersafari.com/52/1/eg70IH.jpg",
    img3: "https://i.pinimg.com/originals/58/1b/72/581b7251f179b0001e658e50dcc5513e.jpg",
    img4: "https://c4.wallpaperflare.com/wallpaper/951/241/300/1986-92-ferrari-interior-supercar-wallpaper-preview.jpg",
  },
  {
    id: "0103",
    Title: "007 WHITE",
    Manufacturer: "Lotus",
    Model: "Esprit",
    Color: { title: "white", hex: "#ffffff" },
    Year: "1986",
    Price: 140000,
    Desc:'The iconic angular wedge bodywork was sketched and brought to life by designer Giorgetto Giugiario, following his own ‘folded paper’ principles. This concept was further refined by Lotus design chief Oliver Winterbottom, finessing the Esprit profile to emphasise its aerodynamic performance and impressively low road stance. What set the Esprit apart was its undeniable visual appeal. Balancing timeless elegance with modern innovations, its sharp, low-slung body lines were as beautiful as they were functional. Guaranteed to turn heads while enhancing aerodynamic efficiency, the Esprit has countless thoughtfully-integrated details – from the now-iconic flip-up headlights to the seamlessly integrated rear spoiler.',
    img1: "https://w0.peakpx.com/wallpaper/649/308/HD-wallpaper-1976-lotus-esprit-coupe-inline-4-car.jpg",
    img2: "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iCf4pTO_MyZ8/v1/1200x712.jpg",
    img3: "https://img.remediosdigitales.com/576a25/lotus-esprit-01/1366_2000.jpg",
    img4: "https://i.pinimg.com/originals/35/d4/cc/35d4cccf282bfdd76b0bec9d4d6a32d0.jpg",
  },
  {
    id: "0104",
    Title: "911",
    Manufacturer: "Porsche",
    Model: "911",
    Color: { title: "black", hex: "#4a4a4a " },
    Year: "1986",
    Price: 200000,
    Desc:'The Porsche 911 remains the epitome of timeless automotive design. There is no other sportscar that has evolved over 60 years and yet has kept the essence of its original design quite like the 911 has, with its perfect proportions, flowing curves and sporty attitude. It’s a continuity of design that is unique in automotive history. The first Porsche 911 set down the basic layout that is still evident in the model today. Its lateral lines, fastback design, the shape of its side windows, free-standing front wings and flat front bonnet remain core features of its design.',
    img1: "https://f7432d8eadcf865aa9d9-9c672a3a4ecaaacdf2fee3b3e6fd2716.ssl.cf3.rackcdn.com/C2299/U8719/IMG_85717-large.jpg",
    img2: "https://pictures.porsche.com/rtt/iris?COSY-EU-100-1711coMvsi60AAt5FwcmBEgA4qP8iBUDxPE3Cb9pNXABuN9dMGF4tl3U0%25z8rMHIspMtwZaiE010iO5M3tCvNzxHceoPa2OySOJUPY1zHTBsN5NWg2dioCARF%25vUqrIauWXsO534eV6iTC6Bzhp4NdTxf4KxJhvauDFmOcuLAlWRDdV24U",
    img3: "https://pictures.porsche.com/rtt/iris?COSY-EU-100-1711coMvsi60AAt5FwcmBEgA4qP8iBUDxPE3Cb9pNXABuN9dMGF4tl3U0%25z8rMH8spMtwZaiE010iO5M3tCvNzxHceoPa2OySOJUPY1zHTBsN5NWg2dioCARF%25vUqrIauWXsO534eV6iTC6Bzhp4NdTxf4KxJhvauDFmOcuLAlWRDdV24U",
    img4: "https://www.topgear.com/sites/default/files/2022/10/2%20Porsche%20911%20GT3%20RS.jpg",
  },
  {
    id: "0105",
    Title: "EL DIABLO",
    Manufacturer: "Lamborghini",
    Model: "Diablo",
    Color: { title: "yellow", hex: "#FBBF24" },
    Year: "1986",
    Price: 300000,
    Desc:'Winning the hearts of fans since day one, the Diablo was officially the fastest production car in the world at launch, capable of a top speed of 325km/h. Its impressive dynamic behaviour was the result of intense development work involving the rally champion Sandro Munari.  The Diablo sports the classic Lamborghini 12-cylinder set-up, with a 5.7-litre engine, four overhead camshafts and four valves per cylinder, equipped with multi-point electronic injection capable of developing 485hp (361kW) and 580Nm of torque, in a rear longitudinal position. ',
    img2: "https://www.hdwallpapers.in/download/lamborghini_lamborghini_diablo_gtr_sport_yellow_car_hd_cars-HD.jpg",
    img1: "https://hips.hearstapps.com/hmg-prod/images/4d8752535a-1280-1588349882.jpg",
    img3: "https://prod.pictures.autoscout24.net/listing-images/ea010a07-9c7b-4e86-80c8-42c332368dae_5485f2ff-6cda-477a-aa0e-97d5e5e057da.jpg/1920x1080.webp",
    img4: "https://www.benlevy.com/auto/meet/supercar20110903/img_6021.jpg",
  },
  {
    id: "0106",
    Title: "ITALIAN BOOMERANG",
    Manufacturer: "Maseratti",
    Model: "Boomerang",
    Color: { title: "silver", hex: "silver" },
    Year: "1971",
    Price: 380000,
    Desc:'A dream car, an extreme, futuristic, almost irrational, definitely beautiful model capable of remaining imprinted on the memory of every single fan: half a century has passed since 9 March 1972, when the Maserati Boomerang made its debut at the Geneva Motor Show. It was a concept created by the renowned hand of Giorgetto Giugiaro and produced by Italdesign.  Maserati Boomerang – a mockup of which made a fleeting appearance at the 1971 Turin Motor Show: only one model was ever made, which would be presented at the Swiss show in 1972 as a registered vehicle that ran perfectly. The base used by Italdesign (chassis and complete mechanics) was a Maserati Bora, with a central eight-cylinder rear engine laid out at 90° that delivered 4,719 cc. It could unleash 310 hp, bringing it close to a top speed of almost 300 km/h. The rear-wheel drive had a five-speed gearbox.',
    img2: "https://www.alfonsofigares.com/wp-content/uploads/2018/07/historia-maserati-boomerang-1.jpg",
    img1: "https://www.techies.es/wp-content/uploads/2022/06/maserati-boomerang.jpg",
    img3: "https://imagebee.org/vehicles/maserati-boomerang/maserati-boomerang-10-1536x1158.jpg",
    img4: "https://cdn.motor1.com/images/mgl/YAWrxq/s1/la-maserati-boomerang.jpg",
  },
  {
    id: "0107",
    Title: "GERMAN RACER",
    Manufacturer: "Porsche",
    Model: "917",
    Color: { title: "blue", hex: "#00A2ff" },
    Year: "1970",
    Price: 450000,
    Desc:'There have been many great Porsche racing cars over the years, but none quite like the 917. With British driver Richard Attwood and German teammate, Hans Herrmann, at the wheel of a 917 K – a car that little more than a year previously was a mere sketch on a drawing board in Stuttgart – Porsche secured its first ever win at the greatest of all endurance races. It was a victory that would herald decades of dominance in the sport for Porsche. The vehicle is a base model that can be piloted as both a long-tail and short-tail version, thanks to a detachable rear section. Spoiler flaps on the front and rear sections are a prominent aerodynamic feature of the car, and are linked to the wheel suspension to change the angle of attack depending on the car’s downforce and lift.',
    img1: "https://hips.hearstapps.com/hmg-prod/images/porsche-917k-oa-front-1579553084.jpg",
    img2: "https://www.agoramodels.com/site/assets/files/4095/porsche917_2.1200x0.jpeg",
    img3: "https://d62-a.sdn.cz/d_62/c_img_F_H/tVGcl/Porsche-917.jpeg?fl=cro,37,0,1884,1060%7Cres,1200,,1%7Cjpg,80,,1",
    img4: "https://c4.wallpaperflare.com/wallpaper/921/242/463/porsche-917-001-concorde-concorde-002-inside-a-car-hd-wallpaper-preview.jpg",
  },
  {
    id: "0108",
    Title: "ITALIAN CHAMP",
    Manufacturer: "Ferrari",
    Model: "250- GTO",
    Color: { title: "red", hex: "#DC2626" },
    Year: "1962",
    Price: 485000,
    Desc:'The Ferrari 250 GTO is marked with an enduring reputation that has stretched far beyond its limited production run in the early 1960s. Known as the Ferrari that most completely embodies the ambitions of the manufacturer, the Ferrari 250 GTO has cemented itself as arguably the most sought-after automobile ever produced. Sporting a thoroughbred V12 engine, a domineering fascia, and the characteristic red adornment, it’s no mystery as to why the Ferrari 250 GTO retains its popularity among automotive enthusiasts. There is no ambiguity behind the popularity of the Ferrari 250 GTO. This model is stylish, powerful, and athletic. The 250 GTO saw immediate success, finishing second in its debut campaign at the 1962 12 Hours of Sebring. This was no surprise, as the V12 engine of the Prancing Horse churned out 300 hp, a 174 mph top speed, and a sub-three-second 0 to 60 time. On and off the track, the Ferrari 250 GTO has continued to dazzle fans, competitors, and critics alike, filling a proverbial trophy cabinet with endless accolades. ',
    img1: "https://images8.alphacoders.com/676/676503.jpg",
    img2: "https://wallpapercave.com/wp/wp3109472.jpg",
    img3: "https://cdnb.artstation.com/p/assets/images/images/041/265/757/large/carlos-bacardi-ferrari-gto-250-300x1688-front-b.jpg?1631209982",
    img4: "https://c4.wallpaperflare.com/wallpaper/209/877/252/1960-250-classic-ferrari-wallpaper-preview.jpg",
  },
  {
    id: "0109",
    Title: "ALL AMERICAN",
    Manufacturer: "Ford",
    Model: "GT-40",
    Color: { title: "blue", hex: "#00A2ff" },
    Year: "1962",
    Price: 485000,
    Desc:'The Ford GT40 history starts after Ford failed to acquire Ferrari, when angered Henry Ford II stated that he "wanted to win Le Mans in 1966". In order to achieve this goal Ford Advanced Vehicles has be formed with the task of creating a cutting-edge GT car - a highly aerodynamic mid-engine coupe built around the 1963 Indianapolis 4.2 liter engine. First prototypes of the car were launched in April 1964 and named GT40 due to the fact the car was 40 inches high. Three Ford GT40s compete at the 1964 Le Mans and despite the fact that none of them finished the race a new race lap record was set of 3:49.4 (131.7 mph).',
    img1: "https://cdn.motor1.com/images/mgl/KjZ6b/s1/ford-gt40-a-escala.webp",
    img2: "https://www.gran-turismo.com/gtsport/livery/4755805615901673000_23.jpg",
    img3: "https://images6.alphacoders.com/329/329227.jpg",
    img4: "https://c4.wallpaperflare.com/wallpaper/846/484/863/1968-classic-ford-gt40-wallpaper-preview.jpg",
  },
  {
    id: "0110",
    Title: "THE LIVING DAYLIGHTS",
    Manufacturer: "Aston Martin",
    Model: "V8",
    Color: { title: "black", hex: "#4a4a4a" },
    Year: "1984",
    Price: 245000,
    Desc:'The Aston Martin V8 Vantage was hailed at its 1977 introduction as “Britain’s First Supercar” for its 170 mph (270 km/h) top speed. Its engine was shared with the Lagonda, but it used high-performance camshafts, increased compression ratio, larger inlet valves and bigger carburettors mounted on new manifolds for increased output.. Straight-line performance was the best of the day, with acceleration from 0–60 mph (97 km/h) in 5.3 seconds, one-tenth of a second quicker than Ferrari’s mighty Daytona!The first series examples produced 375bhp and series specific details such as a blanked bonnet vent and a separate rear spoiler.',
    img2: "https://images4.alphacoders.com/698/698459.jpg",
    img1: "https://www.rswilliams.co.uk/wp-content/uploads/2017/04/12543Front.jpg",
    img3: "https://www.rswilliams.co.uk/wp-content/uploads/2017/04/12543Rear.jpg",
    img4: "https://notoriousluxury.files.wordpress.com/2015/06/us-spec-4.jpg",
  },
  {
    id: "0111",
    Title: "THE LEGEND",
    Manufacturer: "McLaren",
    Model: "F1",
    Color: { title: "silver", hex: "silver" },
    Year: "2012",
    Price: 245000,
    Desc:'Born from a company with a great pedigree in the world of motorsport, but which had never produced a production car for the road, the F1 was designed from the ground up with the ambitious goal of being the best supercar ever built, regardless of its cost.Thanks to conscientious attention to detail, McLaren created a technological tour de force: its engine was initially going to be Honda, but thanks to Paul Rosche it ended up being a 6.1 V12 with 635 HP of BMW origin capable of accelerating from 0 to 100 km/h in 3.2 seconds. When it was delimited in 1998, the three-seater reached 386 km/h, and that is big talk.',
    img1: "https://img.remediosdigitales.com/192c96/1998-mclaren-f11281683_/450_1000.jpeg",
    img2: "https://cdn.autobild.es/sites/navi.axelspringer.es/public/media/image/2022/08/mclaren-f1-2791013.jpg?tf=3840x",
    img3: "https://www.sportscarmarket.com/wp-content/uploads/2019/11/1994-mclaren-f1-rear.jpg",
    img4: "https://i0.wp.com/www.car-revs-daily.com/wp-content/uploads/2015/06/McLaren-F1-GT-Longtail-Silver-3.jpg?ssl=1",
  },
  {
    id: "0118",
    Title: "QUATTRO RALLY ",
    Manufacturer: "Audi",
    Model: "Quattro",
    Color: { title: "yellow", hex: "#FBBF24" },
    Year: "1984",
    Price: 150000,
    Desc:"The Audi Quattro was the first rally car to take advantage of the then-recently changed rules that allowed the use of four-wheel drive in competition racing. It won consecutive competitions for the next two years.[4] To commemorate the success of the original vehicle, all subsequent Audi production automobiles with this four-wheel-drive system were badged with the trademark quattro with a lower case q letter.  The Audi Quattro shared many parts and platform with the Coupé version of the Audi 80 (B2).The quattro was internally designated Typ 85, a production code it shared with the quattro versions of the Audi Coupé. Its characteristic flared wheelarches were styled by Martin Smith. The Audi Quattro also had independent front and rear suspension.",
    img1: 'https://i.etsystatic.com/40704512/r/il/b5bb4d/4641711293/il_1588xN.4641711293_f660.jpg',
    img2: "https://i.etsystatic.com/40704512/r/il/233e1d/4641711765/il_1588xN.4641711765_2hdq.jpg",
    img3: "https://c4.wallpaperflare.com/wallpaper/676/914/507/audi-audi-quattro-car-rally-cars-wallpaper-preview.jpg",
    img4: "https://i.pinimg.com/originals/de/d0/4f/ded04f069e204cfb3fb2b86d4e0e261c.jpg",
  },
  {
    id: "0112",
    Title: "BLUE DANUVE ",
    Manufacturer: "Mercedes - Benz",
    Model: "280 SL",
    Color: { title: "blue", hex: "#00A2ff" },
    Year: "1961",
    Price: 300000,
    Desc:'The Mercedes-Benz 280 SL, also known as the W113, is a classic and iconic two-seat luxury sports car that was produced from 1963 to 1971. The 280 SL was well-regarded during its time, offering a blend of sportiness and luxury. It featured a 2.8-liter inline-six engine and was the most powerful variant of the W113 series. With its independent suspension, power-assisted disc brakes, safety elements, and a comfortable interior with high-quality material it quickly became a popular “Mercedes-Benz”.Besides its sporty yet elegant nature the SL was renowned for its timeless design, characterized by its distinctive "Pagoda" hardtop roof – characterized by its slightly concave and curved shape, resembling the multi-tiered roofs of traditional Asian pagodas – , which slopes downward towards the center. This design element not only added to the cars aesthetic appeal but also improved visibility.The Mercedes-Benz 280 SL remains a unique classic car up until today, known for its combination of elegant design, driving experience, and historical significance within the Mercedes-Benz lineup.',
    img2: "https://cdn.classic-trader.com/I/images/960_720/vehicle_ad_standard_image_8302d7b2cbbdda5d0ceea9a1981378f8.jpg",
    img1: "https://cdn.motor1.com/images/mgl/wGOxL/s1/brabus-restored-classic-mercedes-benz-cars.webp",
    img3: "https://c1.wallpaperflare.com/preview/440/120/1021/car-vintage-mercedes-blue.jpg",
    img4: "https://www.gallery-aaldering.com/wp-content/uploads/gallery/18839104/18839104-57.jpg",
  },
  {
    id: "0113",
    Title: "NAZI REDEEMER ",
    Manufacturer: "VolksWagen",
    Model: "Beetle",
    Color: { title: "black", hex: "#4a4a4a" },
    Year: "1961",
    Price: 200000,
    Desc:'The Beetle was a masterpiece of innovation and economics—it was compact, but practical, and inexpensive to buy and maintain. The car’s curved exterior not only gave it a groundbreaking look, but was aerodynamic, too. Rear-wheel drive and its small stature gave the Beetle excellent handling, particularly when compared to the American land yachts of its day, and the innovative air-cooled engine required less maintenance and was easy to fix.',
    img2: "https://static.boredpanda.com/blog/wp-content/uploads/2020/11/1961-volkswagen-beetle-deluxe-roadster-danni-koldal-fb-png__700.jpg",
    img1: "https://i.pinimg.com/originals/78/9c/b0/789cb0e57558e170e0784158b7eb778e.png",
    img3: "https://e4p7c9i3.stackpathcdn.com/wp-content/uploads/2020/11/14733246_1797157757227484_7108805744060792832_n.jpg?iv=634",
    img4: "https://www.archidesiign.com/wp-content/uploads/2022/07/AD-transformation-of-a-1961-vw-beetle-deluxe-into-a-black-matte-roadster-05.jpg",
  },
  {
    id: "0114",
    Title: "YELLOW DANCER ",
    Manufacturer: "Bugatti",
    Model: "Chiron",
    Color: { title: "yellow", hex: "#FBBF24" },
    Year: "2017",
    Price: 500000,
    Desc:'People who choose cars such as the Chiron do so because they want a vehicle that makes a jaw-dropping impact on the boulevard or at the valet stand—or in front of the Monte Carlo Casino. With its swooping lines and famously stratospheric price, the base Chiron certainly fits the bill. We think this model has what it takes to put a smile on the face of even the most discerning hypercar buyer. The Chiron comes standard with amenities such as quad LED headlights and full power accessories. All Chiron models are motivated by an 8.0-liter 16-cylinder powerplant. This beast of an engine employs four turbochargers to generate a mighty 1500 horsepower and 1180 pound-feet of torque. Bugatti claims that the Chiron makes the dash from zero to 60 mph in a mere 2.3 seconds, and it has a top speed of 261 mph.',
    img1: "https://www.hdcarwallpapers.com/walls/2018_bugatti_chiron_yellow_and_black_4k_2-HD.jpg",
    img2: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/b23e7a68789259.5b699a1594946.jpg",
    img3: "https://c4.wallpaperflare.com/wallpaper/867/112/870/bugatti-salon-2018-chiron-wallpaper-preview.jpg",
    img4: "https://cdnb.artstation.com/p/assets/images/images/049/873/421/large/lukas-wenzhoefer-04-edit.jpg?1653510484",
  },
  {
    id: "0115",
    Title: "MAGNUM ",
    Manufacturer: "Ferrari",
    Model: "308 GTS",
    Color: { title: "red", hex: "#DC2626" },
    Year: "1980",
    Price: 200000,
    Desc:'The Ferrari 308 is one of the most recognizable and iconic cars ever produced. The 308 nameplate made headlines for the first time nearly five decades ago, around a time when the industry’s thirst for high-powered sports cars was insatiable. Not that it’s any different today, but the sports car revolution was relatively more insane back then. The 308 was further popularized on the widespread television series, Magnum, P.I. You might also recall its appearance in the Cannonball Run, the unforgettable 1981 action-comedy flick, where it was driven by Dean Martin and Sammy Davis Jr., who dressed as Catholic priests. Powered by a mid-mounted transverse V-8, the 308 unlocked an entirely new segment for the brand.',
    img1: "https://images4.alphacoders.com/102/1027294.jpg",
    img2: "https://images3.alphacoders.com/102/1027301.jpg",
    img3: "https://besthqwallpapers.com/Uploads/28-11-2019/113368/ferrari-308-gtb-back-view-1979-cars-supercars-1979-ferrari-308.jpg",
    img4: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIWmvNs5kP713mwyoPqjUoZzfpPPwL4zKRQg&usqp=CAU",
  },
  {
    id: "0116",
    Title: "BLUE VELVETTE ",
    Manufacturer: "Chevrolet",
    Model: "Corvette C4",
    Color: { title: "blue", hex: "#00A2ff" },
    Year: "1980",
    Price: 100000,
    Desc:'the new C4 only improved with time." The convertible returned with high-performance engines, exemplified by the 375 HP (380 HP; 280 kW) of the LT5 in the ZR-1. In early March 1990, the ZR-1 would set a new 24-hour-5,000 mile (8,000 km) record for going over 175 mph (282 km/h).Although prices rose, although sales declined, the fourth generation gained its own loyal following.',
    img1: 'https://www.corvsport.com/wp-content/uploads/2017/02/EoraqG-1400x788.jpg',
    img2: "https://i.pinimg.com/550x/16/41/5b/16415b0dac58a26284c9bf4d64868e62.jpg",
    img3: "https://upload.wikimedia.org/wikipedia/commons/6/6d/1980_Blue_Chevy_Corvette_with_486_engine%3B_Custom_Rear.jpg",
    img4: "https://www.joesgoldengasoline.com.au/wp-content/uploads/2020/10/1980-Chevrolet-Corvette-dark-blue-7.jpg",
  },
  {
    id: "0117",
    Title: "SHELBY COBRA ",
    Manufacturer: "Ford",
    Model: "AC Cobra",
    Color: { title: "yellow", hex: "#FBBF24" },
    Year: "1962",
    Price: 200000,
    Desc:'Take a good long look at Carroll Shelbys unrestored original Cobra: Its tiny, especially by todays standards. In fact, its 4 in. shorter, 5 in. narrower and 200 lb. lighter than a first-generation Mazda Miata. Yet, it has a 260-cu.-in. Ford V-8 stuffed under its aluminum hood. The AC Cobra is an Anglo-American sports car built in the years 1962 to 1966 by the manufacturer AC Cars. Contrary to popular belief, this was not the first car to use a lightweight European aluminum chassis and body and a powerful American V8 engine, but it was arguably the most famous.',
    img1: 'https://c4.wallpaperflare.com/wallpaper/356/680/32/shelby-1965-cobra-yellow-wallpaper-preview.jpg',
    img2: "https://i.ytimg.com/vi/L1FXV6bxddc/sddefault.jpg",
    img3: "https://c4.wallpaperflare.com/wallpaper/511/444/982/1965-cars-cobra-shelby-wallpaper-preview.jpg",
    img4: "https://i.pinimg.com/1200x/0a/ac/61/0aac6108cd2a97734b5078fcd7d81d35.jpg",
  },
  
];

export default carsInventory;
